spring:
  jpa.hibernate.ddl-auto: update
  datasource.url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
  cloud.stream.bindings.receiveSensorData-in-0.destination: sensor-data

management.endpoints.web.exposure.include: "*"

title: Sensor Database

logging: 
    level: 
      org: 
        springframework: 
          cloud: INFO 
          integration: INFO 
