apiVersion: carto.run/v1alpha1
kind: ClusterDelivery
metadata:
  name: delivery-act
spec:
  resources:
  - name: source-provider
    params:
    - default: default
      name: serviceAccount
    - name: gitImplementation
      value: go-git
    templateRef:
      kind: ClusterSourceTemplate
      name: delivery-source-template
  - deployment:
      resource: source-provider
    name: deployer
    params:
    - default: default
      name: serviceAccount
    templateRef:
      kind: ClusterDeploymentTemplate
      name: app-deploy
  - name: integration-testing
    deployment:
      resource: deployer
    templateRef:
      kind: ClusterDeploymentTemplate
      name: integration-test
  - name: act-deployment
    deployment:
      resource: integration-testing
    params:
    - default: workload-sa
      name: serviceAccount
    - default: prod
      name: gitops_branch
    - default: supplychain
      name: gitops_user_name
    - default: supplychain
      name: gitops_user_email
    - default: produced by TAP 1.4
      name: gitops_commit_message
    - default: github-workload-token
      name: gitops_ssh_secret
    - default: https://github.com/
      name: gitops_server_address
    - default: timwangvmw
      name: gitops_repository_owner
    - default: k8s_yaml_v1r4
      name: gitops_repository_name
    - default: github
      name: gitops_server_kind
    - default: ""
      name: gitops_commit_branch
    - default: 請 review 後核准
      name: gitops_pull_request_title
    - default: generated by PSO TAP 1.4
      name: gitops_pull_request_body
    templateRef:
      kind: ClusterDeploymentTemplate
      name: deploy-act
  selector:
    app.tanzu.vmware.com/deliverable-type: web
    apps.tanzu.vmware.com/act-tests: "true"
