apiVersion: carto.run/v1alpha1
kind: ClusterDelivery
metadata:
  annotations:
    kapp.k14s.io/identity: v1;/carto.run/ClusterDelivery/delivery-basic;carto.run/v1alpha1
  labels:
  name: delivery-for-acceptance-only
spec:
  resources:
  - name: source-provider
    params:
    - name: serviceAccount
      value: default
    - name: gitImplementation
      value: go-git
    templateRef:
      kind: ClusterSourceTemplate
      name: delivery-source-template
  - deployment:
      resource: source-provider
    name: deployer
    params:
    - name: serviceAccount
      value: default
    templateRef:
      kind: ClusterDeploymentTemplate
      name: app-deploy
  selector:
    app.tanzu.vmware.com/deliverable-type: web
    app.tanzu.vmware.com/deliverable-target: acceptance
