---
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: cnr-tls-wildcard
  namespace: workloads
spec:
  delegations:
  - secretName: tap-ca-secret
    targetNamespaces:
    - "*"
